// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using data_aggregation;

#nullable disable

namespace dataaggregation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230202104805_ChangedAggregationCOlumnType")]
    partial class ChangedAggregationCOlumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("data_aggregation.Apartment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("network");

                    b.Property<string>("ObjGvType")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obj_gv_type");

                    b.Property<string>("ObjNumber")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obj_number");

                    b.Property<string>("ObtName")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obt_name");

                    b.Property<decimal>("PMinus")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("p_minus");

                    b.Property<decimal>("PPlus")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("p_plus");

                    b.Property<string>("PlTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pl_time");

                    b.HasKey("Id");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("data_aggregation.ApartmentAggregated", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("network");

                    b.Property<string>("ObjGvType")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obj_gv_type");

                    b.Property<string>("ObjNumber")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obj_number");

                    b.Property<string>("ObtName")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("obt_name");

                    b.Property<decimal>("PMinusSum")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("p_minus");

                    b.Property<decimal>("PPlusSum")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal")
                        .HasColumnName("p_plus");

                    b.Property<string>("PlTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pl_time");

                    b.HasKey("Id");

                    b.ToTable("ApartmentsAggregated");
                });
#pragma warning restore 612, 618
        }
    }
}
